### ISSUE TITLE
CPU usage goes up outside casting window

### ISSUE THREAD

**Issue by Mellowlynx** [b0mbays/continuously_casting_dashboards#22]
Yesterday afternoon I noticed that the CPU usage goes up every night, starting around 22:00 and ending at 8.
Around 23 a clock I checked trough SSH what processes was running, and saw the name of my Next hub.

At that point I disabled continuously casting and restarted HA. Then the load was gone.

I hope this can be fixed or that I can use a workaround so the load stays normal, but casting is also enabled during the day.

  
Below the CPU load from the HA VM

Last 24 hours:
![image](https://github.com/b0mbays/continuously_casting_dashboards/assets/2348339/1a3f5424-6239-4339-9645-e3150d6645e3)

Last week:
![image](https://github.com/b0mbays/continuously_casting_dashboards/assets/2348339/80d6648a-67d3-4fb7-8b44-acbcdfda2f2f)

**Comment by b0mbays** [comment]
Hey, that is interesting! I've never noticed this but we did have another user open up a [PR](https://github.com/b0mbays/continuously_casting_dashboards/pull/19) that potentially fixes this problem. It might be caused by the cast_delay not being set correctly. I'll try and test the PR's changes asap and get the change merged in which should stop the high CPU usage.

**Comment by Mellowlynx** [comment]
If you like me to test, let me know where and what to change and I will be happy to try it.

**Comment by b0mbays** [comment]
The change is in now, if you restart HA you should see an update for the integration (v.1.2.5). If you could test it and make sure the usage has gone down that would be great 😄

**Comment by Mellowlynx** [comment]
Yay!! it's fixed.
Thanks for the fast update @b0mbays and thanks for the fix @jhbruhn
