### ISSUE TITLE
Incompatible PyYAML version with HA 2023.7.3

### ISSUE THREAD

**Issue by jhbruhn** [b0mbays/continuously_casting_dashboards#29]
Since the latest Home Assistant Upgrade, I am getting this error:
```
 Setup failed for custom integration continuously_casting_dashboards: Requirements for continuously_casting_dashboards not found: ['PyYAML==6.0']. 
```
I am guessing there has been a minor upgrade. Perhaps the dependency can bet set to all versions which have the major version 6?

**Comment by b0mbays** [comment]
Ah damn, yeah.. this can happen occasionally when HA bumps up a pip requirement. I'm out the rest of the day but can take a look tomorrow. In the meantime I'd avoid that version and downgrade for now.

**Comment by m33ts4k0z** [comment]
Hello,

According to the [official documentation](https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-integration-requirements), this requirement is not needed since it exists within the Core requirements. I removed it from the manifest.json of the integration and the casting still works.

**Comment by b0mbays** [comment]
@m33ts4k0z Great, thank you! I've tested this too and this is working on the new update by removing pyYAML. 

I've published a new [release](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.2.6) that should be available after a restart of HA. Please update to get this integration working again on 2023.7.3 👍

**Comment by klasenby** [comment]
> @m33ts4k0z Great, thank you! I've tested this too and this is working on the new update by removing pyYAML.
> 
> I've published a new [release](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.2.6) that should be available after a restart of HA. Please update to get this integration working again on 2023.7.3 👍

When trying to restart to pick up the new version, I get this error message. I also tried redownloading using version 1.2.6 and get the same error.

Failed to restart Home
Assistant
The system cannot restart because the configuration is not valid: Integration error: continuously_casting_dashboards - Requirements for
continuously_casting_dashboards n found: [PYYAML==6.01].

**Comment by b0mbays** [comment]
Unfortunately home assistant will stop you from restarting. You can get around this by doing a full reboot from inside settings 👍 then, the new version will be there, update and restart (or reboot again if it stops you)

**Comment by klasenby** [comment]
I just removed CCD and it's configuration, restarted HA, reinstalled CCD and put the configuration back. All working now!
